-- Q1. What is the total revenue generated by male vs. female customers? 
select gender, sum(purchase_amount) as revenue 
from customer 
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount
from customer 
where discount_applied = "Yes" and purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating), 2)
from customer 
group by item_purchased 
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, round(avg(purchase_amount), 2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status, count(customer_id) as total_customer, avg(purchase_amount) as avg_spend, sum(purchase_amount) as revenue_generation
from customer
group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, round(sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) * 100,2) as discount_rate
from customer group by item_purchased
order by discount_rate desc limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
-- and show the count of each segment. 
with cus_type as (
	select 
    case when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal' end as cust_segment
    from customer
)
select cust_segment, count(*) as no_of_occ
from cus_type
group by cust_segment;


-- Q8. What are the top 3 most purchased products within each category? 
with cust as (
	select item_purchased, category,
		count(customer_id) as count_cust,
        row_number() over (partition by category order by count(customer_id) desc) as rnk
        from customer
        group by item_purchased, category
)
select rnk, category, item_purchased, count_cust from cust where rnk <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(*) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group?
select age_category, sum(purchase_amount) as revenue
from customer
group by age_category
order by sum(purchase_amount) desc;